baseURL = "https://multilingual-hugo.com/"
languageCode = "en-us"
title = "Hugo + Weglot"
theme = "ananke"

SectionPagesMenu = "main"

[params]
  favicon = "/images/favicon-32x32.png"
  site_logo = "/images/weglot.svg"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/LouisBertin"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/gradient.jpg"
  custom_css = ["css/custom.css"]
  recent_posts_number = 2